# Generated by Django 2.2 on 2019-04-30 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='select',
            field=models.BooleanField(default=True),
        ),
    ]
