# Generated by Django 2.2 on 2019-05-01 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20190430_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='select',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Not Selected'), (1, 'Selected Alreday')], default=1),
        ),
    ]
