# Generated by Django 2.2 on 2019-05-06 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20190507_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='food-default.jpg', upload_to='product'),
        ),
    ]
