# Generated by Django 2.2 on 2019-05-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20190507_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='image',
            field=models.ImageField(blank=True, default='place-default.jpg', upload_to='place'),
        ),
    ]
