# Generated by Django 2.2 on 2019-05-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190508_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.PositiveSmallIntegerField(choices=[(0, 'QRDC Taipei'), (1, 'CSMC A Factory'), (2, 'CSMC C Factory'), (3, 'CSMC D Factory'), (4, 'QSMC F4')], default=0),
        ),
    ]
