# Generated by Django 2.1.7 on 2019-05-10 13:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190509_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.PositiveSmallIntegerField(choices=[(0, 'QRDC Taipei'), (1, 'CSMC A Factory'), (2, 'CSMC C Factory'), (3, 'CSMC D Factory'), (4, 'QSMC F4')], default=0, help_text='Choice your current office location'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text="Digits and '+' only.", max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+8860806449'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='subscribe',
            field=models.BooleanField(default=True, help_text='Subscribe for newsletter?'),
        ),
    ]
