# Generated by Django 2.1.7 on 2019-05-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190510_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='photo',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=('main.UserProfile.photo', 'profiles'), verbose_name='Profile Picture'),
        ),
    ]
