# Generated by Django 2.1.7 on 2019-05-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20190514_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='profile_pucture'),
        ),
    ]
