# Generated by Django 2.1.7 on 2019-05-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20190514_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='profile_pucture'),
        ),
    ]
