# Generated by Django 2.1.7 on 2019-05-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20190514_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, default='profile-default.jpg', max_length=255, null=True, upload_to='profile_pucture'),
        ),
    ]
