# Generated by Django 2.1.7 on 2019-05-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20190514_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, default='profile-default.jpg', max_length=255, upload_to='profile_pucture'),
        ),
    ]
