# Generated by Django 2.1.7 on 2019-05-15 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20190515_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(blank=True, default='2000-01-01', null=True),
        ),
    ]
