# Generated by Django 2.2 on 2019-05-20 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_placecategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='location',
        ),
    ]
