# Generated by Django 2.2 on 2019-05-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_userprofile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Male'), (1, 'Female')], default=0),
        ),
    ]
