# Generated by Django 2.2 on 2019-04-30 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='location',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Choose'), (1, 'Factory A'), (2, 'Factory C'), (3, 'Factory D')], default=0),
        ),
    ]
