# Generated by Django 2.2 on 2019-04-30 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='location',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Choose'), (1, 'CSMC-A'), (2, 'CSMC-C'), (3, 'CSMC-D'), (4, 'QSMC-F4')], default=0),
        ),
    ]
